---
language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - "8"
  - "9"
notifications:
  email: false
services:
  - redis-server
after_success:
  - npm i -g coveralls codeclimate-test-reporter
  - coveralls < coverage/lcov.info
  - codeclimate-test-reporter < coverage/lcov.info
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
